# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Go.gitlab-ci.yml

.build_environment:
  image: registry.gitlab.com/jeyran/go-clang-image

variables:
  # Please edit to your GitLab project
  REPO_NAME: gitlab.com/monolith

# The problem is that to be able to use go get, one needs to put
# the repository in the $GOPATH. So for example if your gitlab domain
# is gitlab.com, and that your repository is namespace/project, and
# the default GOPATH being /go, then you'd need to have your
# repository in /go/src/gitlab.com/namespace/project
# Thus, making a symbolic link corrects this.
before_script:
      source .build_info
      && mkdir -p /go/src/$DIRECTORY
      && cp -r $CI_PROJECT_DIR /go/src/$DIRECTORY
      && export GOPATH=/go
      && cd $GOPATH/src/$DIRECTORY/$APP

stages:
  - test
  - build
  - deploy

format:
  stage: test
  tags:
    - exam
  extends: .build_environment
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    
lint:
  stage: test
  tags:
    - exam
  extends: .build_environment
  script:
    - make lint

unit_test:
  stage: test
  tags:
    - exam
  extends: .build_environment
  script:
    - make unit-tests

race_detector:
  stage: test
  tags:
    - exam
  extends: .build_environment
  script:
    - make race

memory_sanitizer:
  stage: test
  extends: .build_environment
  tags:
    - exam
  script:
    - make msan


compile:
  stage: build
  extends: .build_environment
  tags:
    - exam
  script:
    - make build
